// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// linear_regression_example
Eigen::VectorXd linear_regression_example();
RcppExport SEXP _RcppNumericalSolverTEST_linear_regression_example() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(linear_regression_example());
    return rcpp_result_gen;
END_RCPP
}
// rosenbrock_example
Eigen::VectorXd rosenbrock_example();
RcppExport SEXP _RcppNumericalSolverTEST_rosenbrock_example() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rosenbrock_example());
    return rcpp_result_gen;
END_RCPP
}
// nonnegativeleastsquares_example
Eigen::VectorXd nonnegativeleastsquares_example();
RcppExport SEXP _RcppNumericalSolverTEST_nonnegativeleastsquares_example() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nonnegativeleastsquares_example());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppNumericalSolverTEST_linear_regression_example", (DL_FUNC) &_RcppNumericalSolverTEST_linear_regression_example, 0},
    {"_RcppNumericalSolverTEST_rosenbrock_example", (DL_FUNC) &_RcppNumericalSolverTEST_rosenbrock_example, 0},
    {"_RcppNumericalSolverTEST_nonnegativeleastsquares_example", (DL_FUNC) &_RcppNumericalSolverTEST_nonnegativeleastsquares_example, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppNumericalSolverTEST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
