# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title RcppNumericalSolver example
#'
#' @description An example demonstrating RcppNumericalSolver
#'
#' @return Numeric vector
linear_regression_example <- function() {
    .Call(`_RcppNumericalSolverTEST_linear_regression_example`)
}

rosenbrock_example <- function() {
    .Call(`_RcppNumericalSolverTEST_rosenbrock_example`)
}

nonnegativeleastsquares_example <- function() {
    .Call(`_RcppNumericalSolverTEST_nonnegativeleastsquares_example`)
}

