# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Linear regression example
#'
#' @description An example demonstrating linear regression with the RcppNumericalSolver library.
#'
#' @return Numeric vector
linear_regression_example <- function() {
    .Call(`_RcppNumericalSolverTEST_linear_regression_example`)
}

#' @title Rosenbrock example
#'
#' @description An example demonstrating Rosenbrock with the RcppNumericalSolver library.
#'
#' @return Numeric vector
rosenbrock_example <- function() {
    .Call(`_RcppNumericalSolverTEST_rosenbrock_example`)
}

#' @title Non-negative least squares example
#'
#' @description An example demonstrating non-negative least squares with the RcppNumericalSolver library
#'
#' @return Numeric vector
nonnegativeleastsquares_example <- function() {
    .Call(`_RcppNumericalSolverTEST_nonnegativeleastsquares_example`)
}

